const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Camera3D,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.DragnDrop.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Box: 0},
	{InitialX: 0},
	{InitialY: 0},
	{IsMatrix: 0},
	{MatrixAnimationName: 0},
	{DragDrop: 0},
	{Tween: 0},
	{Element: 0},
	{SideBar: 0},
	{Reader: 0},
	{TrashBin: 0},
	{Flash: 0},
	{"3DCamera": 0},
	{Background: 0},
	{Particles: 0},
	{Browser: 0},
	{Touch: 0},
	{PositionX: 0},
	{PositionY: 0},
	{AnimationName: 0},
	{UnlockNew: 0},
	{Elements: 0},
	{IsValid: 0},
	{Text: 0},
	{Element1: 0},
	{Element2: 0},
	{Discoveries: 0}
];

self.InstanceType = {
	Box: class extends self.I3DShapeInstance {},
	Element: class extends self.ISpriteInstance {},
	SideBar: class extends self.ISpriteInstance {},
	Reader: class extends self.ISpriteInstance {},
	TrashBin: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {}
}